### ISSUE TITLE
1.20.6 Support

### ISSUE THREAD

**Issue by Zorklis** [doinkythederp/lan-extender-fabric#34]
### Explain the feature

Would be nice to have a 1.20.6 version, so people can play on LAN servers.

### Ideal solution or implementation

To update to 1.20.6

### [Optional] Alternative solutions or implementations

+even better if it works with Vulkan Mod

**Comment by lewisfm** [comment]
Does this mod work for you? https://modrinth.com/mod/e4mc

**Comment by Zorklis** [comment]
Currently don't have a way to test it with my partner, but at least trying to start the server leads to no crashes on 1.20.6 with a 1.20.2 version so I'll say yeah it does work
